//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Platform.Upgrade.AdminModule.Localization
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    
    internal class SRCategoryAttribute : System.ComponentModel.CategoryAttribute
    {
        public SRCategoryAttribute(string category) : 
                base(category)
        {
        }
        protected override string GetLocalizedString(string value)
        {
            return Sage.Platform.Upgrade.AdminModule.Localization.SR.GetString(value);
        }
    }
    internal class SRDefaultValueAttribute : System.ComponentModel.DefaultValueAttribute
    {
        private bool _replaced;
        public SRDefaultValueAttribute(string value) : 
                base(value)
        {
        }
        public override object Value
        {
            get
            {
                if ((this._replaced == false))
                {
                    base.SetValue(Sage.Platform.Upgrade.AdminModule.Localization.SR.GetString(((string)(base.Value))));
                    this._replaced = true;
                }
                return base.Value;
            }
        }
    }
    internal class SRDescriptionAttribute : System.ComponentModel.DescriptionAttribute
    {
        private bool _replaced;
        public SRDescriptionAttribute(string description) : 
                base(description)
        {
        }
        public override string Description
        {
            get
            {
                if ((this._replaced == false))
                {
                    base.DescriptionValue = Sage.Platform.Upgrade.AdminModule.Localization.SR.GetString(base.Description);
                    this._replaced = true;
                }
                return base.Description;
            }
        }
    }
    [GeneratedCodeAttribute("Sage.VisualStudio.SRGenerator", "1.0.0.0")]
    [DebuggerNonUserCodeAttribute()]
    [CompilerGeneratedAttribute()]
    internal sealed class SR
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;
        public const string MashupUpgradePackage_AddMashupModule_Description = "MashupUpgradePackage_AddMashupModule_Description";
        public const string MashupUpgradePackage_Description = "MashupUpgradePackage_Description";
        public const string QuickFormUpgradePackage_Description = "QuickFormUpgradePackage_Description";
        public const string QuickFormUpgradePackage_MoveSnippetActionMethods_Description = "QuickFormUpgradePackage_MoveSnippetActionMethods_Description";
        public const string SupportFilesMigrationUpgradePackage_CopySupportFilesIntoModel_Description = "SupportFilesMigrationUpgradePackage_CopySupportFilesIntoModel_Description";
        public const string SupportFilesMigrationUpgradePackage_Description = "SupportFilesMigrationUpgradePackage_Description";
        public const string EntityUpgradePackage_Description = "EntityUpgradePackage_Description";
        public const string EntityUpgradePackage_SetLastUpdatedProperty_Description = "EntityUpgradePackage_SetLastUpdatedProperty_Description";
        public const string RelationshipUpgradePackage_Description = "RelationshipUpgradePackage_Description";
        public const string RelationshipUpgradePackage_UpdateFileNameFormat_Description = "RelationshipUpgradePackage_UpdateFileNameFormat_Description";

        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return Sage.Platform.Upgrade.AdminModule.Localization.SR.resourceCulture;
            }
            set
            {
                Sage.Platform.Upgrade.AdminModule.Localization.SR.resourceCulture = value;
            }
        }
        public static string GetString(string name)
        {
            if (object.ReferenceEquals(Sage.Platform.Upgrade.AdminModule.Localization.SR.resourceMan, null))
            {
                Sage.Platform.Upgrade.AdminModule.Localization.SR.resourceMan = new System.Resources.ResourceManager("Sage.Platform.Upgrade.AdminModule.Localization.SR", typeof(Sage.Platform.Upgrade.AdminModule.Localization.SR).Assembly);
            }
            return Sage.Platform.Upgrade.AdminModule.Localization.SR.resourceMan.GetString(name);
        }
    }
    [AttributeUsage(AttributeTargets.All)]
    internal class SRDisplayNameAttribute : System.ComponentModel.DisplayNameAttribute
    {
        private bool _replaced;
        public SRDisplayNameAttribute(string displayname) : 
                base(displayname)
        {
        }
        public override string DisplayName
        {
            get
            {
                if ((this._replaced == false))
                {
                    base.DisplayNameValue = Sage.Platform.Upgrade.AdminModule.Localization.SR.GetString(base.DisplayName);
                    this._replaced = true;
                }
                return base.DisplayName;
            }
        }
    }
}
