//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Platform.Upgrade.AdminModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Platform.Upgrade.AdminModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
               /// <summary>
        ///   Looks up a localized string similar to Unable to find an appropriate last updated property on entity &apos;{0}&apos;..
        /// </summary>
        internal static string EntityUpgradePackage_Unable_to_find_an_appropriate_last_updated_property {
            get {
                return ResourceManager.GetString("EntityUpgradePackage_Unable_to_find_an_appropriate_last_updated_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appending mashup model type name.
        /// </summary>
        internal static string MashupUpgradePackage_Appending_mashup_model_type_name {
            get {
                return ResourceManager.GetString("MashupUpgradePackage_Appending_mashup_model_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating model type names from configuration.
        /// </summary>
        internal static string MashupUpgradePackage_Migrating_model_type_names_from_configuration {
            get {
                return ResourceManager.GetString("MashupUpgradePackage_Migrating_model_type_names_from_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating model type names from project workspace.
        /// </summary>
        internal static string MashupUpgradePackage_Migrating_model_type_names_from_project_workspace {
            get {
                return ResourceManager.GetString("MashupUpgradePackage_Migrating_model_type_names_from_project_workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving method target snippet file: .
        /// </summary>
        internal static string QuickFormUpgradePackage_Moving_method_target_snippet_file {
            get {
                return ResourceManager.GetString("QuickFormUpgradePackage_Moving_method_target_snippet_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving snippet action method file: .
        /// </summary>
        internal static string QuickFormUpgradePackage_Moving_snippet_action_method_file {
            get {
                return ResourceManager.GetString("QuickFormUpgradePackage_Moving_snippet_action_method_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet {0} will need to be manually updated to match the new snippet method prototype..
        /// </summary>
        internal static string QuickFormUpgradePackage_Snippet_will_need_to_be_manually_updated {
            get {
                return ResourceManager.GetString("QuickFormUpgradePackage_Snippet_will_need_to_be_manually_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse method file: .
        /// </summary>
        internal static string QuickFormUpgradePackage_Unable_to_parse_method_file {
            get {
                return ResourceManager.GetString("QuickFormUpgradePackage_Unable_to_parse_method_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving support files to copy..
        /// </summary>
        internal static string SupportFilesMigrationUpgradePackage_Retrieving_support_files_to_copy {
            get {
                return ResourceManager.GetString("SupportFilesMigrationUpgradePackage_Retrieving_support_files_to_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support files path {0} does not exist for portal {1}..
        /// </summary>
        internal static string SupportFilesMigrationUpgradePackage_The_support_files_path_does_not_exist_for_portal {
            get {
                return ResourceManager.GetString("SupportFilesMigrationUpgradePackage_The_support_files_path_does_not_exist_for_por" +
                        "tal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support files path {0} is being copied into the model for portal {1}..
        /// </summary>
        internal static string SupportFilesMigrationUpgradePackage_The_support_files_path_is_being_copied_into_the_model_for_portal {
            get {
                return ResourceManager.GetString("SupportFilesMigrationUpgradePackage_The_support_files_path_is_being_copied_into_t" +
                        "he_model_for_portal", resourceCulture);
            }
        }
 /// <summary>
        ///   Looks up a localized string similar to Deleting model index cache..
        /// </summary>
        internal static string RelationshipUpgradePackage_DeletingModelIndexCache {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackage_DeletingModelIndexCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming {0}.
        /// </summary>
        internal static string RelationshipUpgradePackage_ErrorRenamingRelationship {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackage_ErrorRenamingRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was renamed to {1}..
        /// </summary>
        internal static string RelationshipUpgradePackage_FileWasRenamed {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackage_FileWasRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up all entity Ids..
        /// </summary>
        internal static string RelationshipUpgradePackage_LookingUpEntityIds {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackage_LookingUpEntityIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0}.
        /// </summary>
        internal static string RelationshipUpgradePackage_RenamingRelationshipFile {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackage_RenamingRelationshipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all relationships..
        /// </summary>
        internal static string RelationshipUpgradePackageGettingAllRelationships {
            get {
                return ResourceManager.GetString("RelationshipUpgradePackageGettingAllRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Upgrade Module.
        /// </summary>
        internal static string UpgradeModuleFriendlyName {
            get {
                return ResourceManager.GetString("UpgradeModuleFriendlyName", resourceCulture);
            }
        }
    }
}
